### ISSUE TITLE
Injecting a difficulty only seems to work for one song.

### ISSUE THREAD

**Issue by ItIsIWeeg** [AppleHair/FNF-UnrestDiffs#1]
I'm working on injecting a difficulty for a list of songs from base game (Fresh, DadBattle, Philly Nice, and Guns), and no matter what I do, a couple of errors are thrown at me, and only the first song I start the list with is given the new difficulty. 

Error 1: Error while executing function VariationInjector.setup()#84: EUnknownVariable
UnknownVariable error: Tried to access "variId", an unknown variable or identifier.

Error 2: Error while executing function VariationInjector.onStateChangeEnd()#108: EUnknownVariable
UnknownVariable error: Tried to access "setup", an unknown variable or identifier.

As far as I'm aware, I followed the directions in the provided README files correctly, so I'm not sure why this would be messing up.

**Comment by AppleHair** [comment]
Yes, I know these kind of errors a little too well. This is definitely something I'll need to fix. Thank you for reporting the bug!

**Comment by AppleHair** [comment]
Ok fixed it!

**Comment by ItIsIWeeg** [comment]
Can confirm, everything works now! Thank you!
![screenshot-2024-06-26-11-12-01](https://github.com/AppleHair/FNF-UnrestDiffs/assets/79732045/4a69eb1e-59c7-431f-8269-85ae2219e918)
