### ISSUE TITLE
[ENHANCEMENT]: Add a check before loading a custom variation to Story Mode

### ISSUE THREAD

**Issue by Trayfellow** [AppleHair/FNF-UnrestDiffs#2]
Unrestricted Diffs currently loads all of your custom variations into Story Mode no matter what, if your planning to make your mod just a Freeplay-exclusive (like character remixes) this could be an issue, I'd suggest making Story Mode check if a 'levels-alt' file exists for your custom variation first before making it available to select on Story Mode

**Comment by AppleHair** [comment]
The solution will be different from what you described. Instead of having a difficulty invisible by default, you'll make an alt level data with `visible` being `false` for difficulties / variations you don't want in story mode.

**Comment by AppleHair** [comment]
So I finished it, tested it and it's working just fine. I also made hot reload more stable on story mode in the same commit, so I just released it. Have fun!

**Comment by Trayfellow** [comment]
> So I finished it, tested it and it's working just fine. I also made hot reload more stable on story mode in the same commit, so I just released it. Have fun!

Works well!
