### ISSUE TITLE
Variations dont work

### ISSUE THREAD

**Issue by DarkRazer1** [AppleHair/FNF-UnrestDiffs#3]
Every time I open fnf, I get these errors. I don't know what causes this. The only mods I have that uses your mod is "B-sides port" and "B-sides redux port".
![Capture](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/bf59d77e-492e-49da-b4a0-d57a334d36df)
![Capture2](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/6a4e3c5d-9d72-4363-91fa-11bb0833502c)
![Capture3](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/2b678029-f3f1-49d8-b2e9-ad81500fcbe7)
![Capture4](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/fc86511a-4900-4d69-98bc-1f55fb2aa0d5)
![Capture5](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/4a3c548b-053f-4c2c-a152-18cd5250a35c)
![Capture6](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/b955b81e-0fe4-4b0e-8cdb-351fa2c64160)

**Comment by Sky4580** [comment]
Al

**Comment by DarkRazer1** [comment]
I'm on 4.1 btw

**Comment by AppleHair** [comment]
Screenshot your mods folder + the folders of the mods that use this framework

**Comment by AppleHair** [comment]
Delete all the mods which are related to this framework (Including the framework), re-Install the other mods, while removing the bundled copies of the framework, and then re-install the latest version of the framework. 

Doing this should make everything work as intended. You just need to make sure everything is on the latest version and not mixed with outdated code.

**Comment by DarkRazer1** [comment]
Ok, the mod works now. however, It show this error every time I boot the game
![Capture](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/5d9e3eb6-15e9-4f12-8bb2-c5a3c3423493)
![Capture2](https://github.com/AppleHair/FNF-UnrestDiffs/assets/138380836/c9a40c6b-bc83-4020-ae81-b83585492d93)

**Comment by DarkRazer1** [comment]
Oh, wait. I forgot to update Pico dadbattle mod. oops

**Comment by DarkRazer1** [comment]
Now there's no error's. Thanks
