### ISSUE TITLE
Difficulty Showing Wrong Song Name

### ISSUE THREAD

**Issue by DanintheMine** [AppleHair/FNF-UnrestDiffs#4]
I used the Unrestricted Difficulties mod to implement an erect remix of the song "Stress" from week 7. The song itself works fine, but in the story mode menu and the freeplay menu, the hard difficulty shows the name of the erect remix.
![screenshot-2024-06-30-15-59-41](https://github.com/AppleHair/FNF-UnrestDiffs/assets/155109815/b17027e2-258f-4caf-a12d-e0eafbf39005)
![screenshot-2024-06-30-15-59-55](https://github.com/AppleHair/FNF-UnrestDiffs/assets/155109815/18aca0af-e57d-4d22-bd4b-20a3360341e5)

**Comment by AppleHair** [comment]
Go to your variation's chart file, find empty difficulties and remove them to fix this problem (in your case, you'll find an empty "hard" difficulty in there). This is a bug with the base game, not with this framework.
