### ISSUE TITLE
Alternate Instrumental Feature not working

### ISSUE THREAD

**Issue by SamTheBlueMan** [AppleHair/FNF-UnrestDiffs#7]
The alternate instrumental feature does not work with this mod. It still lets you select the Pico or Bf instrumental for a song however it always loads with the default song data. This happens with every song, and with both Pico and BF mixes.

**Comment by AppleHair** [comment]
Ok, I think I know why this is happening. I'll try to fix it soon.

**Comment by AppleHair** [comment]
Yup, it was what I thought. I just fixed it with [this simple change](https://github.com/AppleHair/FNF-UnrestDiffs/commit/d2024012d406f01aa0ceb6e0854215ac2675c995). Let me know if it works for you.

**Comment by SamTheBlueMan** [comment]
It's all fixed now. Thank you so much!
